"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef } from "react";
import { useProductAnalytics } from "../lib/productAnalytics";
import { AeviaLogo } from "./AeviaLogo";
import styles from "./aevia.module.css";

export function AeviaLanding() {
  const tracked = useRef(false);
  const track = useProductAnalytics();
  useEffect(() => { if (!tracked.current) { tracked.current = true; void track("landing_viewed", { route: "/" }); } }, [track]);
  return <main className={styles.siteShell}>
    <header className={styles.nav}><div className={styles.navInner}><AeviaLogo /><nav className={styles.primaryNav} aria-label="Primary navigation"><a href="#specialists">The Assistants</a><a href="#conversations">WhatsApp Live</a><a href="#compass">Living Context</a><a href="#principles">Architectural Ethos</a></nav><Link className={styles.navCta} href="/onboarding" onClick={() => void track("cta_clicked", { route: "/", outcome: "header" })}>Get started <span>beta</span></Link></div></header>
    <section className={styles.hero}><div className={styles.heroInner}>
      <div className={styles.heroCopy}><p className={styles.betaPill}><i />Private Beta Cohort <span>Care &amp; Kitchen Intelligence</span></p><h1>The everyday things you care about. <em>Taken care of, by Aevia.</em></h1><p className={styles.heroLead}>Where your parents&apos; wellbeing and the daily rhythm of your kitchen find effortless harmony—delivered quietly on WhatsApp.</p><div className={styles.metrics}><div><strong>10+ Hours</strong><span>Quiet time returned weekly</span></div><div><strong>Zero Apps</strong><span>Native to family WhatsApp</span></div></div><div className={styles.heroActions}><Link className={styles.primaryButton} href="/onboarding" onClick={() => void track("cta_clicked", { route: "/", outcome: "hero" })}>Meet Aevia — Get started →</Link><a className={styles.secondaryButton} href="#specialists">Explore the Sanctuary</a></div></div>
      <div className={styles.heroVisual}><Image src="/aevia/landing-hero.jpg" alt="A family together at home" fill priority sizes="(max-width: 900px) 100vw, 50vw" /><div className={styles.liveCaption}><span>● Household Harmony Live</span><em>Morning routine in sync</em></div><aside className={styles.syncCard}><strong>Aevia Domestic Sync</strong><span>08:14 AM</span><p>Breakfast tailored · Papa&apos;s medicine taken quietly</p><small>Cook notified of low oil &amp; substituted methi without interruption.</small></aside></div>
    </div></section>
    <section className={styles.editorialSection} id="specialists"><SectionIntro eyebrow="Architectural Domestic Agents" title="Two distinct intelligences. One seamless home." text="Engineered specifically for the delicate cultural and operational rhythms of Indian households." /><div className={styles.agentStack}>
      <AgentCard image="/aevia/tarla-intro.jpg" alt="A cook preparing a household meal" badge="Culinary Lead" eyebrow="01 · Culinary Intelligence" title="Tarla — Culinary Sanctuary" text="Solves the daily ‘kya banega?’ friction. Personalised seasonal meals, adapts for pantry constraints, and coordinates smoothly with your cook." moment="Palak nahi hai. Tarla changes the dish, recalculates quantities, and keeps the rest of the plan steady." tags={["Meal Architecture", "Cook Coordination", "Nutrition"]} />
      <AgentCard image="/aevia/mitra-intro.jpg" alt="Older adults walking in a garden" badge="Care Companion" eyebrow="02 · Reverent Care" title="Mitra — Reverent Care for Parents" text="Sensitive reminders, daily pulse checks, routine care, medicine schedules with customary Indian warmth and deep respect. Never clinical, always familial." moment="Papa, evening walk ka time ho gaya. Ho gayi walk?" tags={["Medicine Reminders", "Routine Scheduling", "Natural & Warm"]} />
      <article className={styles.combinedCard}><p>Combined Intelligence</p><h3>The Complete Residence: When Mitra &amp; Tarla breathe together.</h3><span>When your parent&apos;s routine or support needs affect today&apos;s kitchen context, your household transitions from reactive stress into an enduring sanctuary of calm.</span><blockquote>“It feels like having an auntie, cultural elder and head of kitchen rehearsing everything in the background with absolute grace.”</blockquote></article>
    </div></section>
    <section className={styles.inlineCta}><p>Ready to introduce quiet order into your family home?</p><Link href="/onboarding">Say hello to Aevia →</Link></section>
    <section className={styles.conversations} id="conversations"><SectionIntro eyebrow="Conversational Artistry" title="Real conversations on WhatsApp." text="Simple. Natural. In your language. No apps for parents or cooks to relearn." /><div className={styles.chatGrid}><Chat title="Mitra · Parent Check-in" lines={["Papa, evening walk ka time ho gaya. Ho gayi walk?", "Haan beta, ho gayi.", "Achha, theek hai. Thank you."]} outcome="Completion gently confirmed. Family stays informed." /><Chat title="Tarla · Kitchen Coordinator" lines={["Namaste. Aaj ka meal plan taiyaar hai.", "Palak nahi hai.", "Koi baat nahi. Palak ki jagah bhindi kar lete hain. Baaki plan same rahega."]} outcome="Meal substitution resolved without interrupting the family." /></div></section>
    <section className={styles.compass} id="compass"><SectionIntro eyebrow="Living Household Compass" title={<>Setup once in whispers.<br />Remembered forever.</>} text="Your family should not have to repeat daily instructions like a broken record. Aevia quietly builds a private contextual compass for your home." /><ol className={styles.compassSteps}><li><b>1</b><div><strong>Share Your Household Once</strong><span>People, routines, food rules and the names your family naturally uses.</span></div></li><li><b>2</b><div><strong>Assign Care &amp; Help on WhatsApp</strong><span>Choose Mitra, Tarla, or both, and who each specialist may contact.</span></div></li><li><b>3</b><div><strong>Let Intelligence remember silently</strong><span>Aevia keeps the context you approve and brings you in only when needed.</span></div></li></ol><div className={styles.memoryCard}><header><strong>Living Household Context</strong><span>Sync complete</span></header><div><p><b>Care &amp; routine preferences</b><small>Daily walk · familiar medicine names</small></p><p><b>Daily wellness cadence</b><small>Morning and evening check-ins</small></p><p><b>Culinary boundaries</b><small>Restrictions · pantry · seasonal foods</small></p><p><b>Allergy protocol</b><small>Hard stops before preferences</small></p></div></div></section>
    <section className={styles.principles} id="principles"><div><p>Architectural Ethos</p><h2>Helpful enough to act.<br />Careful enough to ask.</h2><span>A sanctuary is built on respect, boundaries, and discretion. We treat your family home as sacred space.</span><ol><li><b>01</b><strong>Remembers context</strong><span>Maintains nuances so your household does not repeat routines or food preferences.</span></li><li><b>02</b><strong>Knows when to ask</strong><span>Sensitive boundaries and edge cases are never guessed.</span></li><li><b>03</b><strong>Lives where life is</strong><span>Works through WhatsApp, where family and domestic staff are already comfortable.</span></li><li><b>04</b><strong>Honest closed beta</strong><span>Important information and decisions should still be reviewed.</span></li></ol></div></section>
    <section className={styles.closing}><div><p>Invitation to the cohort</p><h2>Let Aevia bring quiet order to the home you cherish.</h2><span>Private onboarding is currently underway for select family households.</span><Link href="/onboarding">Begin private access →</Link><small>No credit card needed · WhatsApp-first · Limited family cohort</small></div></section>
    <footer className={styles.footer}><AeviaLogo compact /><nav><Link href="/privacy">Household Privacy</Link><Link href="/terms">Sanctuary Terms</Link><Link href="/beta">Beta Protocol</Link></nav><p>© 2026 Aevia Household Technologies.</p></footer>
  </main>;
}

function SectionIntro({ eyebrow, title, text }: { eyebrow: string; title: React.ReactNode; text: string }) { return <header className={styles.sectionIntro}><p>{eyebrow}</p><h2>{title}</h2><span>{text}</span></header>; }
function AgentCard({ image, alt, badge, eyebrow, title, text, moment, tags }: { image: string; alt: string; badge: string; eyebrow: string; title: string; text: string; moment: string; tags: string[] }) { return <article className={styles.agentCard}><div className={styles.agentImage}><Image src={image} alt={alt} fill sizes="(max-width: 900px) 100vw, 62vw" /><span>{badge}</span></div><div className={styles.agentCopy}><p>{eyebrow}</p><h3>{title}</h3><span>{text}</span><blockquote><small>Live conflict moment</small><strong>{moment}</strong></blockquote><div>{tags.map((tag) => <i key={tag}>{tag}</i>)}</div></div></article>; }
function Chat({ title, lines, outcome }: { title: string; lines: string[]; outcome: string }) { return <article className={styles.chatCard}><header><div><strong>{title}</strong><span>Simple, familiar conversation</span></div><em>WhatsApp live</em></header><div>{lines.map((line, index) => <p key={line} data-side={index === 1 ? "reply" : "agent"}><small>{index === 1 ? "Reply" : "Aevia"}</small>{line}</p>)}</div><footer>● {outcome}</footer></article>; }
